// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVhk5Jnocduuje6ptQ6G_m-KA7gGiRuaY',
    appId: '1:22266777909:android:3c5e88ba27f55a4b66bc7c',
    messagingSenderId: '22266777909',
    projectId: 'grocery-delivery-app-demo',
    storageBucket: 'grocery-delivery-app-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0s0ehv1gcLQed0yyQI2efJIMJ5rUcbVw',
    appId: '1:22266777909:ios:0e1fce34f93d4f3e66bc7c',
    messagingSenderId: '22266777909',
    projectId: 'grocery-delivery-app-demo',
    storageBucket: 'grocery-delivery-app-demo.appspot.com',
    iosClientId: '22266777909-orr3429ttpl8kfhald25evbihhkop56h.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0s0ehv1gcLQed0yyQI2efJIMJ5rUcbVw',
    appId: '1:22266777909:ios:a87fd369e841f7bd66bc7c',
    messagingSenderId: '22266777909',
    projectId: 'grocery-delivery-app-demo',
    storageBucket: 'grocery-delivery-app-demo.appspot.com',
    iosClientId: '22266777909-58mfacbn688u2d31s2b6jtomdofu31g6.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryDeliveryApp.RunnerTests',
  );
}
